<a href="https://colab.research.google.com/github/ZeusDeev/Analisis-de-Datos---Curso/blob/proyecto_curso/analisis_datos_p2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas - Tratamiento de Datos**

In [23]:
import pandas as pd
import numpy as np

# Creación del diccionario
data = {
    'Nombre': ['Mateo', 'Esteban', 'Leonardo', 'Wily', 'Carlos','Mateo','Julio','Abraham','Ramiro','Casimiro','Manuel','Jose','Marcos','Francisco','Alex'],
    'Apellido': ['Perez', None, 'Dicaprio', 'Wonka', 'Pereira',None,'Mato','Cach','Alfalfa','Socorro','Maquiavelo',None,'Estrada', 'Luna', None],
    'Edad': [20, 32, np.nan, 25, np.nan, 23, 60, 34, 20, 29,50, np.nan, 18, 25, 42],
    'Ciudad': ['CDMX', None, None, 'CDMX', 'Delicias', 'Guadalajara', None, 'Matamoros', 'Los Cabos', 'Tenochtitlan', 'Jalisco', None, 'Guanajuato', 'Tuxtla', 'Puebla']
}

# Convertimos nuestro diccionario a un dataframe
personal_data = pd.DataFrame(data)

In [24]:
# Exportación del dataframe
personal_data.to_csv('personal_data.csv')

In [25]:
# Importacion del dataframe
personal_data = pd.read_csv('personal_data.csv')

In [26]:
# Eliminamos columna extra que sale unnamed
personal_data.drop(personal_data.columns[0], axis=1)

       Nombre    Apellido  Edad        Ciudad
0       Mateo       Perez  20.0          CDMX
1     Esteban         NaN  32.0           NaN
2    Leonardo    Dicaprio   NaN           NaN
3        Wily       Wonka  25.0          CDMX
4      Carlos     Pereira   NaN      Delicias
5       Mateo         NaN  23.0   Guadalajara
6       Julio        Mato  60.0           NaN
7     Abraham        Cach  34.0     Matamoros
8      Ramiro     Alfalfa  20.0     Los Cabos
9    Casimiro     Socorro  29.0  Tenochtitlan
10     Manuel  Maquiavelo  50.0       Jalisco
11       Jose         NaN   NaN           NaN
12     Marcos     Estrada  18.0    Guanajuato
13  Francisco        Luna  25.0        Tuxtla
14       Alex         NaN  42.0        Puebla

In [28]:
# Rellenar valores Faltantes con fillna
personal_data_fillna = personal_data.fillna({
    'Edad': personal_data['Edad'].mean(), # si edad esta vacio, accedemos a nuestro df en la columna edad para cambiarlo por la media
    'Ciudad': 'Desconocida' # si ciudad esta vacia, se cambia por desconocida
})

personal_data_fillna #imprime

    Unnamed: 0     Nombre    Apellido  Edad        Ciudad
0            0      Mateo       Perez  20.0          CDMX
1            1    Esteban         NaN  32.0   Desconocida
2            2   Leonardo    Dicaprio  31.5   Desconocida
3            3       Wily       Wonka  25.0          CDMX
4            4     Carlos     Pereira  31.5      Delicias
5            5      Mateo         NaN  23.0   Guadalajara
6            6      Julio        Mato  60.0   Desconocida
7            7    Abraham        Cach  34.0     Matamoros
8            8     Ramiro     Alfalfa  20.0     Los Cabos
9            9   Casimiro     Socorro  29.0  Tenochtitlan
10          10     Manuel  Maquiavelo  50.0       Jalisco
11          11       Jose         NaN  31.5   Desconocida
12          12     Marcos     Estrada  18.0    Guanajuato
13          13  Francisco        Luna  25.0        Tuxtla
14          14       Alex         NaN  42.0        Puebla

In [29]:
# Si notamos que apesar de rellenar nuestros valores faltantes o sabemos que puede
# afectar a nuestra muestra, podemos aplicar los siguiente, usando dropna:

persona_data_dropna = personal_data.dropna() #elimina todos los datos con valores nulos, esto aplica para toda la fila sin importar solo sea un valor faltante
persona_data_dropna #imprime

    Unnamed: 0     Nombre    Apellido  Edad        Ciudad
0            0      Mateo       Perez  20.0          CDMX
3            3       Wily       Wonka  25.0          CDMX
7            7    Abraham        Cach  34.0     Matamoros
8            8     Ramiro     Alfalfa  20.0     Los Cabos
9            9   Casimiro     Socorro  29.0  Tenochtitlan
10          10     Manuel  Maquiavelo  50.0       Jalisco
12          12     Marcos     Estrada  18.0    Guanajuato
13          13  Francisco        Luna  25.0        Tuxtla

In [35]:
# Remplazar valores especificos de alguna columna usando replace

# Igual, otra manera disponible para rellenar valores nulos, puede ser con
# un diccionario, como con fillna pero en este caso seleccionando un tipo especifico
# cono np.nan, None, etc; Seguido de la palabra que deseamos remplazar

personal_data_replace = personal_data.replace({
    'Ciudad': {None: 'Desconocida'}, #si ciudad contien el valor None, cambia a 'Desconocida'
    'Edad': {np.nan: personal_data['Edad'].mean()} #si edad tiene valores NaN, accedemos a nuestro df en la columna edad para cambiarlo por la media
})

personal_data_replace #imprime

    Unnamed: 0     Nombre    Apellido  Edad        Ciudad
0            0      Mateo       Perez  20.0          CDMX
1            1    Esteban         NaN  32.0   Desconocida
2            2   Leonardo    Dicaprio  31.5   Desconocida
3            3       Wily       Wonka  25.0          CDMX
4            4     Carlos     Pereira  31.5      Delicias
5            5      Mateo         NaN  23.0   Guadalajara
6            6      Julio        Mato  60.0   Desconocida
7            7    Abraham        Cach  34.0     Matamoros
8            8     Ramiro     Alfalfa  20.0     Los Cabos
9            9   Casimiro     Socorro  29.0  Tenochtitlan
10          10     Manuel  Maquiavelo  50.0       Jalisco
11          11       Jose         NaN  31.5   Desconocida
12          12     Marcos     Estrada  18.0    Guanajuato
13          13  Francisco        Luna  25.0        Tuxtla
14          14       Alex         NaN  42.0        Puebla

In [37]:
# Rellenado de datos faltantes por medio de la interpolacion o bien usando interpolate

personal_data_interpolate = personal_data.copy() #Hacemos una copia de nuestra anterior data, para rellenar valores nulos, guiandose de lo anterior
personal_data_interpolate['Edad'] = personal_data['Edad'].interpolate() # seleccionamos la columna con valores nulos y despues seleccionamos nuestro data origial, y aplicamos interpolate

personal_data_interpolate #imprime

    Unnamed: 0     Nombre    Apellido  Edad        Ciudad
0            0      Mateo       Perez  20.0          CDMX
1            1    Esteban         NaN  32.0           NaN
2            2   Leonardo    Dicaprio  28.5           NaN
3            3       Wily       Wonka  25.0          CDMX
4            4     Carlos     Pereira  24.0      Delicias
5            5      Mateo         NaN  23.0   Guadalajara
6            6      Julio        Mato  60.0           NaN
7            7    Abraham        Cach  34.0     Matamoros
8            8     Ramiro     Alfalfa  20.0     Los Cabos
9            9   Casimiro     Socorro  29.0  Tenochtitlan
10          10     Manuel  Maquiavelo  50.0       Jalisco
11          11       Jose         NaN  34.0           NaN
12          12     Marcos     Estrada  18.0    Guanajuato
13          13  Francisco        Luna  25.0        Tuxtla
14          14       Alex         NaN  42.0        Puebla

# **Otra maneras de resolver datos duplicados**

In [39]:
# Generarmos un df con datos duplicados


df_duplicado = {
    'Nombre': ['Mateo', 'Juan', 'Mateo', 'Zeus', 'Zeus'],
    'Edad' : [22, 24, 22, 20, 20],
    'Ciudad' : ['CDMX', 'Cancun', 'CDMX', 'Monterrey', 'Monterrey']
}

#pasamos de diccionario a dataframe
df_duplicado = pd.DataFrame(df_duplicado)

#imprimimos
df_duplicado

  Nombre  Edad     Ciudad
0  Mateo    22       CDMX
1   Juan    24     Cancun
2  Mateo    22       CDMX
3   Zeus    20  Monterrey
4   Zeus    20  Monterrey

In [41]:
# Elimanos datos duplicados con drop_duplicates()

# cramos un df nuevo no duplicado, pasamos nuestro df duplicado para asignarle drop_duplicates() para cometer la solucion de duplicacion
df_no_duplicado = df_duplicado.drop_duplicates()
df_no_duplicado #imprimimos

  Nombre  Edad     Ciudad
0  Mateo    22       CDMX
1   Juan    24     Cancun
3   Zeus    20  Monterrey

## **Un tip es que igual si deseamos podemos cambiar el titulo de nuestras columnas**

In [42]:
# Cambiamos el titulo de nuestras columnas de español a ingles usando rename.

df_renombrado =  df_no_duplicado.rename(columns={  #creamos un df nuevo, pasando nuestro df anterior o actual, para usar lrename seguido de columns y renombrar por medio de diccionario
    'Nombre':'Name',
    'Edad':'Age',
    'Ciudad':'City'
})

df_renombrado #imprime

    Name  Age       City
0  Mateo   22       CDMX
1   Juan   24     Cancun
3   Zeus   20  Monterrey

## **De igual manera, podemos ordenar nuestras columnas**

In [44]:
# Ordenamiento de columnas

columnas_ordenadas = ['City', 'Age', 'Name'] #ordenamos como queremos las columnas
df_ordenado = df_renombrado[columnas_ordenadas] #Despues creamos un df ordenado por medio de nuestro df actual asigandole las columans ordenadas

df_ordenado #imprimimos

        City  Age   Name
0       CDMX   22  Mateo
1     Cancun   24   Juan
3  Monterrey   20   Zeus