<a href="https://colab.research.google.com/github/ZeusDeev/Analisis-de-Datos---Curso/blob/proyecto_curso/analisis_datos_p3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Agrupacion de datos**

In [15]:
import pandas as pd
import numpy as np


# Creación del diccionario
data = {
    'Nombre': ['Mateo', 'Esteban', 'Leonardo', 'Wily', 'Carlos','Mateo','Julio','Abraham','Ramiro','Casimiro','Manuel','Jose','Marcos','Francisco','Alex'],
    'Apellido': ['Perez', None, 'Dicaprio', 'Wonka', 'Pereira',None,'Mato','Cach','Alfalfa','Socorro','Maquiavelo',None,'Estrada', 'Luna', None],
    'Edad': [20, 32, np.nan, 25, np.nan, 23, 60, 34, 20, 29,50, np.nan, 18, 25, 42],
    'Ciudad': ['CDMX', None, 'Guadalaja', 'CDMX', 'Delicias', 'Guadalajara', None, 'Matamoros', 'Los Cabos', 'Tenochtitlan', 'Jalisco', 'Los Cabos', 'Guanajuato', 'Tuxtla', 'Puebla'],
    'Puntuacion': [80, 90, 85, 78, 50, 60, 45, 88, 95, 74, 67, 85, 34, 56, 99]
    }

data = pd.DataFrame(data)
data

       Nombre    Apellido  Edad        Ciudad  Puntuacion
0       Mateo       Perez  20.0          CDMX          80
1     Esteban        None  32.0          None          90
2    Leonardo    Dicaprio   NaN     Guadalaja          85
3        Wily       Wonka  25.0          CDMX          78
4      Carlos     Pereira   NaN      Delicias          50
5       Mateo        None  23.0   Guadalajara          60
6       Julio        Mato  60.0          None          45
7     Abraham        Cach  34.0     Matamoros          88
8      Ramiro     Alfalfa  20.0     Los Cabos          95
9    Casimiro     Socorro  29.0  Tenochtitlan          74
10     Manuel  Maquiavelo  50.0       Jalisco          67
11       Jose        None   NaN     Los Cabos          85
12     Marcos     Estrada  18.0    Guanajuato          34
13  Francisco        Luna  25.0        Tuxtla          56
14       Alex        None  42.0        Puebla          99

# **Limpieza de datos ( conceptos aplicados anteriormente)**

Antes de iniciar con el agrupamiento limpiaremos los datos, datos que son compuestos como nulos, usa la opcion que mas te parezca viable

In [21]:
data_clean = data.replace({
    'Edad': {np.nan : data['Edad'].mean()},
    'Ciudad': {None : data['Ciudad'].mode()},
    'Apellido' : {None : 'Desconocido'}
})

data_clean

       Nombre     Apellido  Edad        Ciudad  Puntuacion
0       Mateo        Perez  20.0          CDMX          80
1     Esteban  Desconocido  32.0          CDMX          90
2    Leonardo     Dicaprio  31.5     Guadalaja          85
3        Wily        Wonka  25.0          CDMX          78
4      Carlos      Pereira  31.5      Delicias          50
5       Mateo  Desconocido  23.0   Guadalajara          60
6       Julio         Mato  60.0     Los Cabos          45
7     Abraham         Cach  34.0     Matamoros          88
8      Ramiro      Alfalfa  20.0     Los Cabos          95
9    Casimiro      Socorro  29.0  Tenochtitlan          74
10     Manuel   Maquiavelo  50.0       Jalisco          67
11       Jose  Desconocido  31.5     Los Cabos          85
12     Marcos      Estrada  18.0    Guanajuato          34
13  Francisco         Luna  25.0        Tuxtla          56
14       Alex  Desconocido  42.0        Puebla          99

## Este ejercicio de agrupación nos regresa un diccionario según la ciudad donde viven las personas, por ejemplo, el índice 0 y 3 viven en CDMX

In [9]:
# Agrupa los datos por la columna 'Ciudad'
grouped = data.groupby('Ciudad')

# Imprime los grupos resultantes por 'Ciudad'
print(grouped.groups)

{'CDMX': [0, 3], 'Delicias': [4], 'Guadalaja': [2], 'Guadalajara': [5], 'Guanajuato': [12], 'Jalisco': [10], 'Los Cabos': [8, 11], 'Matamoros': [7], 'Puebla': [14], 'Tenochtitlan': [9], 'Tuxtla': [13]}

## **Otra manera puede ser con el agg:**

Con el groupby agruparas los registros por ciudades , con la funcion agg y la opcion "count" contaras cada registro que exista por ciudad

In [10]:
data.groupby("Ciudad")["Ciudad"].agg(["count"])

              count
Ciudad
CDMX              2
Delicias          1
Guadalaja         1
Guadalajara       1
Guanajuato        1
Jalisco           1
Los Cabos         2
Matamoros         1
Puebla            1
Tenochtitlan      1
Tuxtla            1