<a href="https://colab.research.google.com/github/ZeusDeev/Analisis-de-Datos---Curso/blob/proyecto_curso/analisis_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Series y DataFrame con pandas.

Una serie es una estructura de datos unidimencional que permite almacenar cualquier tipo de datos.

Por otro lado los dataframe son estructura de datos bidimencionales que pueden contener multiples columnas y filas de datos y ambos pueden ser creados apartir de listas,diccionarios o arreglos de numpy.

In [1]:
import pandas as pd

In [ ]:
#Series
numeros = [1,2,3,4]
series = pd.Series(numeros)
print(series)

0    1
1    2
2    3
3    4
dtype: int64

 ## DataFrame con Pandas:


 En un **dataframe** podemos crear desde un diccionario, colocando primeramente el indice de la tabla, es decir el encabezado de nuestra columna, seguido de una lista para colocar nuestros valores.

In [2]:
#DataFrame

datos = {
    'Nombre':['Juan','Maria','Pedro','Abraham'],
    'Edad':[15,20,12,4],
    'Ciudad':['Lima','Arequipa','Lima','Carrillo Puerto']
}


#Genera un DataFrame apartir de un diccionario.

df = pd.DataFrame(datos)
print(df)

    Nombre  Edad           Ciudad
0     Juan    15             Lima
1    Maria    20         Arequipa
2    Pedro    12             Lima
3  Abraham     4  Carrillo Puerto

###Exporta Dataframe como archivo csv.

In [4]:
df.to_csv('datos.csv')

### Importa un DataFrame

In [5]:
df = pd.read_csv('datos.csv', index_col = 0)
# df = df.drop(df.columns[0], axis=1) #con df.drop, eliminamos la columna 0 que salia por defecto, aplicando en todos los campos por medio de axis=1;
df

    Nombre  Edad           Ciudad
0     Juan    15             Lima
1    Maria    20         Arequipa
2    Pedro    12             Lima
3  Abraham     4  Carrillo Puerto

## **Manipulación de datos con pandas**

In [ ]:
#Seleccionar una columna

nombres = df['Nombre']
nombres

0       Juan
1      Maria
2      Pedro
3    Abraham
Name: Nombre, dtype: object

In [ ]:
#Seleccionar una o más columna

fisrt_column = df[['Nombre','Ciudad']]
fisrt_column

    Nombre           Ciudad
0     Juan             Lima
1    Maria         Arequipa
2    Pedro             Lima
3  Abraham  Carrillo Puerto

In [ ]:
#Filtrar por indice
df.loc[3]

Nombre            Abraham
Edad                    4
Ciudad    Carrillo Puerto
Name: 3, dtype: object

In [ ]:
#Filtrar por condición
df[df['Edad'] < 5]

    Nombre  Edad           Ciudad
3  Abraham     4  Carrillo Puerto

In [ ]:
#Filtrar con Query

# df.query('Ciudad == "Lima"')
df.query('Edad > 10')

  Nombre  Edad    Ciudad
0   Juan    15      Lima
1  Maria    20  Arequipa
2  Pedro    12      Lima

In [ ]:
# Filtra por nombre especificos usando isin

df[df['Nombre'].isin(['Juan','Abraham','Maria'])]

    Nombre  Edad           Ciudad
0     Juan    15             Lima
1    Maria    20         Arequipa
3  Abraham     4  Carrillo Puerto

In [ ]:
# Filtrar por ciudad usando isin

df[df['Ciudad'].isin(['Lima'])]

  Nombre  Edad Ciudad
0   Juan    15   Lima
2  Pedro    12   Lima

In [ ]:
# Filtrado por funcion considerando solo 5 caracteres de nombre

def filtrado_caracter(nombre):
  return len(nombre) == 5

df[df['Nombre'].apply(filtrado_caracter)]

  Nombre  Edad    Ciudad
1  Maria    20  Arequipa
2  Pedro    12      Lima

In [8]:
# Crea una funcion que me permita encontrar las personas con edad menor a 15,
# ademas de considerar que los caracteres en nombres sean menor o igual a 5.

def encontrar_persona(edad, nombre):
  return (edad <= 15) & (nombre.str.len() <= 5)



filter = df[encontrar_persona(df['Edad'], df['Nombre'])]
filter

  Nombre  Edad Ciudad
0   Juan    15   Lima
2  Pedro    12   Lima

In [11]:
# Filtrar por edades etre 25 y 35 años

df[df['Edad'].between(12,20)]

  Nombre  Edad    Ciudad
0   Juan    15      Lima
1  Maria    20  Arequipa
2  Pedro    12      Lima